name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger this on push to the main branch
  pull_request:
    branches:
      - main  # Trigger this on PR to the main branch
jobs:
  build:
    runs-on: windows-latest  # Change from ubuntu-latest to windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --headless

      - name: Check if tests passed
        if: success()
        run: echo "Cypress tests passed. Proceeding with merge."
