name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger this on push to the main branch
  pull_request:
    branches:
      - main  # Trigger this on PR to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up .NET (for your ASP.NET project)
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'  # Specify the .NET version you're using

      # Install .NET dependencies
      - name: Restore .NET dependencies
        run: dotnet restore

      # Build the .NET project
      - name: Build the project
        run: dotnet build --configuration Release

      # Install Node.js (required for Cypress)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the version of Node.js that fits your project

      # Install project dependencies (including Cypress)
      - name: Install dependencies
        run: npm install

      # Run Cypress tests in headless mode
      - name: Run Cypress tests
        run: npx cypress run --headless

      # If Cypress tests pass, continue, otherwise fail the job
      - name: Check if tests passed
        if: success()
        run: echo "Cypress tests passed. Proceeding with merge."

  # You can add more jobs for things like deployment or notifications, as needed.
