name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger this on push to the main branch
  pull_request:
    branches:
      - main  # Trigger this on PR to the main branch
jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up .NET SDK
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'

      # Step 3: Restore .NET dependencies
      - name: Restore .NET dependencies
        run: dotnet restore

      # Step 4: Build the ASP.NET project
      # - name: Build the project
      #   run: dotnet build --configuration Release

          
      # Step 5: Set up Node.js for Cypress
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Step 6: Install Node.js dependencies
      - name: Install dependencies
        run: npm install

      # Step 7: Run Cypress tests in headless mode
      - name: Run Cypress tests
        run: npx cypress run --headless --component

      # Step 8: Check if tests passed and proceed
      - name: Check if tests passed
        if: success()
        run: echo "Cypress tests passed. Proceeding with merge."
